name: GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - run: pip install -r requirements.txt

    - run: mkdocs build

    - name: Push docs to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages
